import 'package:flutter/material.dart';
import 'package:sembast/sembast.dart';
import 'package:samadhan_app/services/database_service.dart';

class AttendanceRecord {
  final int id;
  final DateTime date;
  final Map<int, bool> attendance; // studentId -> isPresent

  AttendanceRecord({required this.id, required this.date, required this.attendance});

  factory AttendanceRecord.fromMap(Map<String, dynamic> map, int id) {
    return AttendanceRecord(
      id: id,
      date: DateTime.parse(map['date']),
      attendance: (map['attendance'] as Map<String, dynamic>).map((key, value) => MapEntry(int.parse(key), value as bool)),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'date': date.toIso8601String(),
      'attendance': attendance.map((key, value) => MapEntry(key.toString(), value)),
    };
  }
}

class AttendanceProvider with ChangeNotifier {
  final _attendanceStore = intMapStoreFactory.store('attendance');
  final DatabaseService _dbService = DatabaseService();

  List<AttendanceRecord> _attendanceRecords = [];
  List<AttendanceRecord> get attendanceRecords => _attendanceRecords;

  Future<void> saveAttendance(Map<int, bool> attendance) async {
    final db = await _dbService.database;
    final record = AttendanceRecord(id: 0, date: DateTime.now(), attendance: attendance); // ID will be generated by sembast
    await _attendanceStore.add(db, record.toMap());
    await fetchAttendanceRecords(); // Refetch to keep the list in sync
  }

  Future<void> fetchAttendanceRecords() async {
    final db = await _dbService.database;
    final snapshots = await _attendanceStore.find(db, finder: Finder(sortOrders: [SortOrder(Field.key, false)])); // Sort by date descending
    _attendanceRecords = snapshots.map((snapshot) {
      return AttendanceRecord.fromMap(snapshot.value, snapshot.key);
    }).toList();
    notifyListeners();
  }

  Future<List<AttendanceRecord>> fetchAttendanceRecordsByDateRange(DateTime startDate, DateTime endDate) async {
    final db = await _dbService.database;
    final Finder finder = Finder(
      filter: Filter.and([
        Filter.greaterThanOrEquals('date', startDate.toIso8601String()),
        Filter.lessThanOrEquals('date', endDate.toIso8601String()),
      ]),
      sortOrders: [SortOrder('date', false)],
    );
    final snapshots = await _attendanceStore.find(db, finder: finder);
    return snapshots.map((snapshot) {
      return AttendanceRecord.fromMap(snapshot.value, snapshot.key);
    }).toList();
  }
}
